name: 'Patch files'
description: 'A simple action to patch JSON/XML files'
author: 'Utkarsh Shigihalli'

inputs:
  filesType:
    description: "Type of files this action should patch: `xml` or `json`. Defaults to `json`."
    default: "json"
  files:
    description: 'Required. Files to scan. e.g., testfiles/**/*.json'
    required: true
  patch-syntax:
    description: 'Required. Use the quick patch syntax to patch files. Refer readme for more info.'
    required: true
  output-patched-file:
    description: 'Output patched file to the logs. Default is true'
    default: true
  fail-if-no-files-patched:
    description: 'Fail if no files are patched. Default is false'
    default: false
  fail-if-error:
    description: 'Set false to warn if error occurs or set true to fail the action. Default is false'
    default: false
  
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: file-text
  color: blue